import java.util.ArrayList;
import java.util.List;

public class Main {

    public static void main(String[] args) {
//        System.out.println("Hello World!");
        String[] listMakanan = {
                "Telur",
                "Tahu",
                "Es Teh",
                "Lontong",
                "Jenang",
                "Punten",
                "Krupuk",
                "Sayur Pecel",
                "Daging Kambing",
                "Air Putih",
                "Nasi",
                "Es Teh",
                "Nasi",
                "Daging Kambing",
                "Air Putih",
                "Nasi",
                "Ayam Lodeh",
                "Nasi",
                "Sayur Lodeh",
                "Air Putih",
                "Air Putih",
                "Nasi",
                "Ayam Lodho",
                "Soto",
                "Telur",
                "Ayam",
                "Nasi",
                "Sayur",
                "Telur",
                "Nasi",
                "Ayam",
                "Soto",
                "Es Teh",
                "Nasi",
                "Bergedel",
                "Sop",
                "Air Putih",
                "Nasi",
                "Sayur Lodeh",
                "Nasi",
                "Lodeh",
                "Pentol",
                "Es Teh",
                "Iga penyet",
                "Nasi",
                "Pepsi",
                "Ayam Krispi",
                "Nasi",
                "Pepsi",
                "Ayam Krispi",
                "Nasi",
                "Air Putih",
                "Nasi",
                "Kulit Kambing",
                "Air Putih",
                "Nasi",
                "Kulit Kambing",
                "Sayur Pecel",
                "Nasi",
                "Air Putih",
                "Nasi",
                "Sayur Pecel",
                "Air Putih",
                "Nasi",
                "Sayur Asem",
                "Lontong",
                "Telur",
                "Tahu",
                "Krupuk",
                "Air Putih",
                "Sayur Asem",
                "Nasi",
                "Roti Pokis",
                "Air Putih",
                "Bakso",
                "Srabi",
                "Air Putih",
                "Krupuk",
                "Nasi",
                "Daging Kambing",
                "Nasi",
                "Daging Kambing",
                "Krupuk",
                "Air Putih",
                "Semangka",
                "Krupuk",
                "Air Putih",
                "Nasi",
                "Daging Kambing",
                "Sayur",
                "Ayam",
                "Nasi",
                "Es Teh",
                "Air Putih",
                "Daging Kambing",
                "Nasi",
                "Nasi",
                "Air Putih",
                "Ayam",
                "Es Teh",
                "Sayur",
                "Ayam",
                "Nasi",
                "Sayur",
                "Nasi",
                "Air Putih",
                "Telur",
                "Sambel Pecel",
                "Krupuk",
                "Air Putih",
                "Sayur",
                "Nasi",
                "Sayur",
                "Nasi",
                "Air Putih",
                "Tempe",
                "Air Putih",
                "Sayur",
                "Nasi",
                "Air Putih",
                "Kaldu Rawon",
                "Daging Kambing",
                "Nasi",
                "Air Putih",
                "Kaldu Rawon",
                "Daging Kambing",
                "Nasi",
                "Air Putih",
                "Sayur",
                "Nasi",
                "Air Putih",
                "Sayur",
                "Nasi",
                "Nasi",
                "Air Putih",
                "Sayur",
                "Ayam",
                "Air Putih",
                "Sayur",
                "Nasi",
                "Air Putih",
                "Sayur",
                "Ayam",
                "Nasi",
                "Air Putih",
                "Sayur",
                "Ayam",
                "Nasi",
                "Es Teh",
                "Sayur",
                "Ayam",
                "Mie",
                "Sayur",
                "Nasi",
                "Air Putih",
                "Telur",
                "Teh Hangat",
                "Snack",
                "Tongkol",
                "Nasi",
                "Air Putih",
                "Sayur",
                "Pentol",
                "Snack",
                "Air Putih",
                "Tongkol",
                "Sayur",
                "Nasi",
                "Mie Instan",
                "Nasi",
                "Air Putih",
                "Telur",
                "Ayam",
                "Nasi",
                "Air Putih",
                "Sayur",
                "Air Putih",
                "Ayam",
                "Sayur",
                "Nasi",
                "Nasi",
                "Air Putih",
                "Sayur",
                "Air Putih",
                "Ikan",
                "Sayur",
                "Nasi",
                "Pentol",
                "Nasi",
                "Air Putih",
                "Ikan",
                "Air Putih",
                "Sayur",
                "Nasi",
                "Air Putih",
                "Sayur",
                "Nasi",
                "Nasi",
                "Ayam",
                "Air Putih",
                "Air Putih",
                "Bumbu Sate",
                "Nasi",
                "Ayam",
                "Ayam",
                "Air Putih",
                "Nasi",
                "Air Putih",
                "Nasi",
                "Sate",
                "Nasi",
                "Sayur",
                "Air Putih",
                "Air Putih",
                "Sayur",
                "Nasi",
                "Air Putih",
                "Nasi",
                "Sayur",
                "Air Putih",
                "Sayur",
                "Nasi",
                "Air Putih",
                "Sayur",
                "Nasi",
                "Air Putih",
                "Sayur",
                "Cecek",
                "Nasi",
                "Nasi",
                "Air Putih",
                "Cecek",
                "Ayam",
                "Air Putih",
                "Ayam",
                "Nasi"
        };

        String[] kodeMakanan = {
                "Air Putih",
                "Aqua",
                "Ayam",
                "Ayam Bakar",
                "Ayam Kampung",
                "Ayam Krispi",
                "Ayam Lodeh",
                "Ayam Lodho",
                "Bakso",
                "Bergedel",
                "Bumbu Sate",
                "Cecek",
                "Dadar Jagung",
                "Daging Ayam",
                "Daging Kambing",
                "Energen",
                "Es Jeruk",
                "Es Teh",
                "Eskrim Walls",
                "Float",
                "Friench Fries",
                "Gule",
                "Iga penyet",
                "Ikan",
                "Jamur",
                "Jenang",
                "Kaldu Rawon",
                "Kerupuk Kaleng",
                "Krupuk",
                "Kulit Kambing",
                "Lodeh",
                "Lontong",
                "Mie",
                "Mie Instan",
                "Nasi",
                "Nugget",
                "Oat",
                "Oreo",
                "Pentol",
                "Pepsi",
                "Punten",
                "Roti Pokis",
                "Sambel Pecel",
                "Sate",
                "Sayur",
                "Sayur Asem",
                "Sayur Bayam",
                "Sayur Lodeh",
                "Sayur Pecel",
                "Semangka",
                "Snack",
                "Sop",
                "Soto",
                "Srabi",
                "Susu Indomilk",
                "Tahu",
                "Teh Hangat",
                "Telur",
                "Tempe",
                "Tongkol"

        };

        for (int i = 0; i < listMakanan.length; i++) {

            for (int j = 0; j < kodeMakanan.length; j++) {
                if (listMakanan[i] == kodeMakanan[j]) {
                    System.out.println(j+1);
                } else {

                }
            }
        }

    }
}
